### ISSUE TITLE
Ability to configure http client

### ISSUE THREAD

**Issue by jenakan** [unit-finance/unit-ruby-sdk#40]
Hi team, so excited to see a ruby sdk!

I see that `HttpHelper` is making requests through `Net::Http`. Would love to be able to inject a `faraday` client instead, so that we can pull in our own desired logging, retry strategy, tracing and error monitoring.

I understand the desire to keep the library clean of any opinionated gems. Hopefully a configurable property will assuage that concern.

**Comment by nirmaoz** [comment]
Hi @jenakan, 
Thanks for this suggestion!
What api would you like to see for configuring the SDK to use Faraday?

**Comment by Yaellever** [comment]
Closed due to inactivity
